### ISSUE TITLE
Use another vocabulatory than Publish/Republish

### ISSUE THREAD

**Issue by devcrafting** [DevLyon/mixter#16]
Could be something like Quack, or Meow or Whinny, as a reminder of Tweet ;)

- [x] JS
- [x] C#
- [x] Java
- [x] PHP

**Comment by fpellet** [comment]
+1 Quack
I am working on js version. So if no order against, then I use this word tomorrow :)

**Comment by fpellet** [comment]
JS OK on v2 : https://github.com/DevLyon/mixter/tree/js/v2/full

**Comment by fpellet** [comment]
c# ok on v2

**Comment by fpellet** [comment]
ok for all languages
