### ISSUE TITLE
Java annotations : Add comments

### ISSUE THREAD

**Issue by fpellet** [DevLyon/mixter#22]
Java annotations are liked, but participants would have more comments to explain concepts directly in the code.

We can also add link to the article in the source, and reuse the same content

**Comment by jeantil** [comment]
I added definitions, explanations and links to content related to each annotated concept. you can review the updates in 
https://github.com/DevLyon/mixter/tree/java/v2.1/domain/src/main/java/mixter/doc

This is a first draft based on my understanding, I am pretty sure the discussion will teach me a lot :)

**Comment by fpellet** [comment]
I try on https://github.com/DevLyon/mixter/tree/csharp/v2.2
Comments in csharp aren't good

Php and js haven't attributes

**Comment by fpellet** [comment]
Done on csharp
I also added to the commands and queries
