### ISSUE TITLE
[Scala] Test 4 Step 4 : Test is not constistent

### ISSUE THREAD

**Issue by Xephi** [DevLyon/mixter#41]
Actually, in case of a requake, the test named "notify followers when a followee requacks a message" (https://github.com/DevLyon/mixter/blob/scala/v2.1/domain/src/test/scala/mixter/domain/subscription/handlers/NotifyFollowerOfFolloweeMessageSpec.scala#L31), ask us to notify followers of the author message instead of followers of the requacker message 

Potential fix (https://github.com/DevLyon/mixter/blob/scala/v2.1/domain/src/test/scala/mixter/domain/subscription/handlers/NotifyFollowerOfFolloweeMessageSpec.scala#L35) : 
```diff
--- followerRepository.saveFollower(AuthorId, AFollowerId)
+++ followerRepository.saveFollower(RequackerId, AFollowerId)
```

**Comment by fpellet** [comment]
done
