### ISSUE TITLE
Improve instructions slide

### ISSUE THREAD

**Issue by jeantil** [DevLyon/mixter#6]
- [x] Users should not change the tests or the infrastructure code. the solution is necessarily in the core code
- [x] Users can look at the Identity context implementation to get a feeling of how to do the implementation
- [x] Improve introduction to explain the business and what the code of the workshop is all about.

**Comment by devcrafting** [comment]
I think we should put it in a reveal.js presentation (with screenshot of PPT schema for Event Storming)

**Comment by fpellet** [comment]
Ready in slides branch
