### ISSUE TITLE
Remove reply message, associated events and commands

### ISSUE THREAD

**Issue by jeantil** [DevLyon/mixter#7]
It adds quite a bit of complexity to the exercise without much additional insight in the design.

- [x] Java
- [x] Javascript
- [x] C#
- [x] PHP

This is a "master" issue to be updated for each language merged and closed once all languages have been updated.

**Comment by fpellet** [comment]
Js ok

**Comment by fpellet** [comment]
C# ok with v2

**Comment by fpellet** [comment]
Ok for all languages
