### ISSUE TITLE
Normalize the exercise across languages

### ISSUE THREAD

**Issue by jeantil** [DevLyon/mixter#8]
Currently there are minor variations across the 4 languages. 

including 

- [ ] no class needs to be created in js, only the implementation. there is little insight to be gained in implementing an event.
- [ ] ???

**Comment by fpellet** [comment]
the version js is updated. You can use this branch as reference

**Comment by fpellet** [comment]
csharp synchronise with js

**Comment by devcrafting** [comment]
Misunderstanding on this issue : I understood that there IS insight in implementing classes like events, subscription aggregate...else trainee only have to fill in the hole, a more or less a no brain exercise...
Having to create classes makes you wonder why you are creating them, if they exist, you don't really wonder how they appear...

**Comment by jeantil** [comment]
I thinks this has been done for v2, close ?
